### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package

### ISSUE THREAD

**Issue by rawbin-** [RexSkz/json-diff-kit#9] opened 2022-12-15 07:23 UTC
install the package with pnpm add json-diff-kit 
and run the demo
<img width="938" alt="image" src="https://user-images.githubusercontent.com/8169783/207798137-0a633159-8a25-4dd8-bb8f-9424c07f4124.png">

demo code: nodejs 19.2 // mytest.mjs
```
import { Differ,Viewer } from 'json-diff-kit';
console.log(Differ,Viewer)

```

**Comment by alexturpin** [comment] 2022-12-19 16:40
Duplicate of #4

**Closed** 2023-07-09 15:37 UTC
